import type { Locale } from "@/lib/i18n";

export const officialMessages = {
  en: {
    nav: { home: "Home", services: "Services", work: "Our work", story: "Our story", reviews: "Reviews", contact: "Contact", rewards: "Rewards", promo: "Offers", book: "Book now" },
    announcement: { label: "7TH ANNIVERSARY", action: "Discover the celebration" },
    hero: { eyebrow: "MEZZANAIL NAIL STUDIO · MALAYSIA", title: "Nail care, elevated to a modern ritual.", body: "Precision-led nail artistry and considered care in a calm, contemporary studio.", primary: "Book an appointment", secondary: "Explore our services", note: "Thoughtful service · Refined finish · Lasting confidence" },
    campaign: { eyebrow: "20TH JULY — 15TH SEPTEMBER 2026", title: "Seven years of beauty, shared with you.", body: "Discover anniversary-only privileges, member rewards and special surprises created to thank our Mezzanail Nail Studio community.", primary: "Book the anniversary edit", secondary: "View anniversary rewards" },
    booking: { eyebrow: "YOUR APPOINTMENT", title: "Beautifully simple, from booking to finish.", body: "Choose your preferred service and speak directly with our studio team. Every booking link is managed in one place, with no third-party branding in your experience.", points: ["Direct studio confirmation", "Personalised service guidance", "Transparent appointment details"], primary: "Reserve your visit", secondary: "Ask on WhatsApp" },
    app: { eyebrow: "THE MEZZANAIL NAIL STUDIO APP", title: "Your Mezzanail Nail Studio experience, always within reach.", body: "Manage membership privileges, discover offers and stay connected with the studio.", ios: "Download for iPhone", android: "Download for Android" },
    services: { eyebrow: "SERVICES", title: "Care shaped around you.", body: "From refined essentials to advanced nail artistry, each service is delivered with precision and respect for nail health.", viewAll: "View all services", learn: "Learn more", items: [
      ["Hand care", "Manicure rituals, gel colour and considered finishing."],
      ["Foot care", "Pedicure care designed for comfort, polish and renewal."],
      ["Nail extensions", "Balanced structure, elegant length and a natural-looking finish."],
      ["Callus Removal", "Professional callus and FootLogix treatments for smoother, more comfortable feet."],
      ["Half Leg Waxing", "Upper or lower half-leg waxing for a smooth, clean finish."]
    ]},
    gallery: { eyebrow: "SELECTED WORK", title: "Quiet details. Distinct expression.", body: "A selection of Mezzanail Nail Studio finishes, from clean neutrals to editorial statement sets.", cta: "View more on Instagram", alts: ["White signature nail art", "Silver nail extensions", "Black editorial manicure", "Chrome neutral manicure", "Mezzanail Nail Studio signature campaign", "Minimal neutral manicure"] },
    reviews: { eyebrow: "GOOGLE REVIEWS", title: "Trusted for the details that matter.", body: "Client feedback, presented clearly and linked to our verified review destination.", rating: "Client rating", based: "Based on verified Google reviews", cta: "Read all Google reviews", leave: "Leave a review", cards: [["Meticulous service and a beautiful finish. The experience always feels calm and considered.", "Alicia T."], ["The team listens, explains each step and never rushes the appointment.", "Nur A."], ["Consistently polished work with excellent attention to nail health.", "Mei Lin C."]] },
    story: { eyebrow: "OUR STORY", title: "Modern nail care, defined by restraint.", body: "Mezzanail Nail Studio was created in Malaysia around one belief: luxury is not excess, but attention. We pair technical discipline with a calm, personal experience so every client leaves feeling considered.", primary: "Discover our story", secondary: "Meet us in studio" },
    contact: { eyebrow: "VISIT MEZZANAIL NAIL STUDIO", title: "Your next appointment begins here.", body: "Contact our studio team for service recommendations, appointment availability or membership support.", address: "Studio", hours: "Opening hours", phone: "Contact", map: "Open in Maps", book: "Book an appointment", whatsapp: "WhatsApp our team" },
    footer: { line: "Modern nail care, made personal.", explore: "Explore", connect: "Connect", studio: "Studio", privacy: "Privacy", terms: "Terms", copyright: "© 2026 Mezzanail Nail Studio. All rights reserved." },
    pages: {
      services: { eyebrow: "SERVICE MENU", title: "Precision care for hands and feet.", body: "Explore our complete official service menu with current prices and listed durations before booking.", cta: "Discuss your service" },
      about: { eyebrow: "MEZZANAIL NAIL STUDIO, MALAYSIA", title: "A studio built around attention.", body: "Our approach is contemporary, precise and quietly personal. From consultation to final finish, every detail is designed to feel effortless.", values: [["Precision", "Technique and finishing are treated with equal care."], ["Wellbeing", "Nail health and client comfort guide every decision."], ["Restraint", "A refined result never needs unnecessary excess."]], cta: "Plan your visit" },
      contact: { eyebrow: "CONTACT & BOOKING", title: "Speak with our studio team.", body: "Tell us the service, preferred date and time you have in mind. We will confirm availability directly.", formTitle: "Before you message", steps: ["Choose a service category", "Share your preferred date and time", "Receive confirmation from our team"] }
    }
  },
  zh: {
    nav: { home: "首页", services: "服务", work: "作品", story: "品牌故事", reviews: "评价", contact: "联系", rewards: "会员礼遇", promo: "促销", book: "立即预约" },
    announcement: { label: "七周年庆典", action: "查看周年活动" },
    hero: { eyebrow: "MEZZANAIL NAIL STUDIO · 马来西亚", title: "让美甲护理，成为现代精致仪式。", body: "以专业技术、细致美甲艺术与舒适空间，带来从容而高级的护理体验。", primary: "预约服务", secondary: "查看服务项目", note: "细致服务 · 精准呈现 · 长久自信" },
    campaign: { eyebrow: "2026年7月20日 — 9月15日", title: "七年美丽时光，与你共同分享。", body: "探索周年限定礼遇、会员回馈与惊喜活动，感谢每一位 Mezzanail Nail Studio 顾客一路相伴。", primary: "预约周年限定服务", secondary: "查看周年礼遇" },
    booking: { eyebrow: "预约服务", title: "从预约到完成，每一步都简单清晰。", body: "选择理想服务并直接联系门店团队。所有预约链接统一管理，顾客界面不显示第三方品牌。", points: ["门店直接确认", "个性化服务建议", "清晰预约详情"], primary: "预留到店时间", secondary: "WhatsApp 咨询" },
    app: { eyebrow: "MEZZANAIL NAIL STUDIO APP", title: "随时掌握你的 Mezzanail Nail Studio 专属体验。", body: "管理会员礼遇、查看优惠，并与门店保持联系。", ios: "iPhone 下载", android: "Android 下载" },
    services: { eyebrow: "服务项目", title: "围绕你的需求，细致护理。", body: "从精致基础护理到进阶美甲艺术，每项服务都兼顾技术与指甲健康。", viewAll: "查看全部服务", learn: "了解更多", items: [["手部护理", "修甲护理、色胶与细致收尾。"], ["足部护理", "兼顾舒适、精致与焕新的足部护理。"], ["美甲延伸", "结构平衡、优雅长度与自然效果。"], ["去茧护理", "专业去茧与 FootLogix 护理，让双足更平滑舒适。"], ["半腿蜜蜡脱毛", "大腿或小腿蜜蜡脱毛，带来干净平滑的效果。"]] },
    gallery: { eyebrow: "精选作品", title: "安静细节，鲜明表达。", body: "从干净裸色到编辑感造型，精选 Mezzanail Nail Studio 美甲作品。", cta: "前往 Instagram 查看更多", alts: ["白色精致美甲", "银色延伸美甲", "黑色编辑感美甲", "裸色镜面美甲", "Mezzanail Nail Studio 品牌作品", "极简裸色美甲"] },
    reviews: { eyebrow: "GOOGLE 评价", title: "因为重视细节，而获得信任。", body: "清晰呈现顾客反馈，并连接至 Google 评价页面。", rating: "顾客评分", based: "来自经验证的 Google 评价", cta: "查看全部 Google 评价", leave: "留下评价", cards: [["服务非常细致，效果漂亮，整个体验安静而周到。", "Alicia T."], ["团队会认真倾听并解释每个步骤，预约过程从不仓促。", "Nur A."], ["作品一直很精致，也非常重视指甲健康。", "Mei Lin C."]] },
    story: { eyebrow: "品牌故事", title: "以克制，定义现代美甲护理。", body: "Mezzanail Nail Studio 创立于马来西亚，始终相信奢华不是堆砌，而是专注。我们以专业技术与从容体验，让每位顾客都感受到被认真对待。", primary: "了解品牌故事", secondary: "到店体验" },
    contact: { eyebrow: "到访 MEZZANAIL NAIL STUDIO", title: "下一次精致体验，从这里开始。", body: "如需服务建议、预约时间或会员协助，请直接联系门店团队。", address: "门店", hours: "营业时间", phone: "联系方式", map: "打开地图", book: "预约服务", whatsapp: "WhatsApp 联系团队" },
    footer: { line: "现代美甲护理，因你而专属。", explore: "探索", connect: "关注", studio: "门店", privacy: "隐私", terms: "条款", copyright: "© 2026 Mezzanail Nail Studio。保留所有权利。" },
    pages: { services: { eyebrow: "服务目录", title: "为双手与双足而设的精准护理。", body: "预约前可浏览完整官方服务清单、最新价格与已标注的预计时长。", cta: "咨询适合的服务" }, about: { eyebrow: "MEZZANAIL NAIL STUDIO · 马来西亚", title: "一间围绕细节而生的工作室。", body: "我们的方式现代、精准且充满个人关怀。从咨询到完成，每个细节都自然流畅。", values: [["精准", "同样重视专业技术与最终呈现。"], ["健康", "每个决定都以指甲健康和顾客舒适为先。"], ["克制", "真正精致的结果，无需多余堆砌。"]], cta: "计划到店" }, contact: { eyebrow: "联系与预约", title: "直接联系门店团队。", body: "告诉我们理想服务、日期与时间，我们将直接确认预约。", formTitle: "联系前请准备", steps: ["选择服务类别", "提供理想日期和时间", "等待团队确认"] } }
  },
  ms: {
    nav: { home: "Utama", services: "Servis", work: "Hasil kami", story: "Kisah kami", reviews: "Ulasan", contact: "Hubungi", rewards: "Ganjaran", promo: "Promosi", book: "Tempah sekarang" },
    announcement: { label: "ULANG TAHUN KE-7", action: "Lihat sambutan kami" },
    hero: { eyebrow: "MEZZANAIL NAIL STUDIO · MALAYSIA", title: "Penjagaan kuku sebagai ritual moden.", body: "Seni kuku berketepatan tinggi dan penjagaan teliti dalam studio yang tenang dan kontemporari.", primary: "Tempah janji temu", secondary: "Lihat servis kami", note: "Layanan teliti · Hasil kemas · Keyakinan berpanjangan" },
    campaign: { eyebrow: "20 JULAI — 15 SEPTEMBER 2026", title: "Tujuh tahun keindahan, dikongsi bersama anda.", body: "Temui keistimewaan ulang tahun, ganjaran ahli dan kejutan istimewa sebagai penghargaan kepada komuniti Mezzanail Nail Studio.", primary: "Tempah pilihan ulang tahun", secondary: "Lihat ganjaran ulang tahun" },
    booking: { eyebrow: "JANJI TEMU ANDA", title: "Mudah dan jelas, dari tempahan hingga selesai.", body: "Pilih servis anda dan hubungi pasukan studio secara langsung. Semua pautan tempahan diurus di satu tempat tanpa jenama pihak ketiga pada pengalaman pelanggan.", points: ["Pengesahan terus daripada studio", "Cadangan servis peribadi", "Butiran janji temu yang jelas"], primary: "Simpan masa kunjungan", secondary: "Tanya melalui WhatsApp" },
    app: { eyebrow: "APLIKASI MEZZANAIL NAIL STUDIO", title: "Pengalaman Mezzanail Nail Studio sentiasa dekat.", body: "Urus keistimewaan ahli, temui tawaran dan kekal berhubung dengan studio.", ios: "Muat turun untuk iPhone", android: "Muat turun untuk Android" },
    services: { eyebrow: "SERVIS", title: "Penjagaan yang dibentuk untuk anda.", body: "Daripada penjagaan asas hingga seni kuku lanjutan, setiap servis mengutamakan ketepatan dan kesihatan kuku.", viewAll: "Lihat semua servis", learn: "Ketahui lebih lanjut", items: [["Penjagaan tangan", "Ritual manicure, warna gel dan kemasan teliti."], ["Penjagaan kaki", "Pedicure untuk keselesaan, kekemasan dan pembaharuan."], ["Sambungan kuku", "Struktur seimbang, panjang elegan dan hasil semula jadi."], ["Pembuangan Kulit Keras", "Rawatan callus dan FootLogix untuk kaki yang lebih licin dan selesa."], ["Waxing Separuh Kaki", "Waxing bahagian atas atau bawah kaki untuk hasil yang licin dan kemas."]] },
    gallery: { eyebrow: "HASIL PILIHAN", title: "Perincian tenang. Ekspresi tersendiri.", body: "Pilihan hasil Mezzanail Nail Studio, daripada neutral bersih hingga gaya editorial.", cta: "Lihat lagi di Instagram", alts: ["Seni kuku putih", "Sambungan kuku perak", "Manicure editorial hitam", "Manicure neutral krom", "Kempen signature Mezzanail Nail Studio", "Manicure neutral minimal"] },
    reviews: { eyebrow: "ULASAN GOOGLE", title: "Dipercayai untuk butiran yang penting.", body: "Maklum balas pelanggan yang jelas dan dipautkan ke destinasi ulasan kami.", rating: "Penilaian pelanggan", based: "Berdasarkan ulasan Google yang disahkan", cta: "Baca semua ulasan Google", leave: "Tulis ulasan", cards: [["Servis sangat teliti dan hasilnya cantik. Pengalaman sentiasa tenang dan prihatin.", "Alicia T."], ["Pasukan mendengar, menerangkan setiap langkah dan tidak pernah tergesa-gesa.", "Nur A."], ["Hasil sentiasa kemas dengan perhatian tinggi pada kesihatan kuku.", "Mei Lin C."]] },
    story: { eyebrow: "KISAH KAMI", title: "Penjagaan kuku moden, ditakrifkan oleh kesederhanaan.", body: "Mezzanail Nail Studio diasaskan di Malaysia atas satu kepercayaan: kemewahan bukan berlebihan, tetapi perhatian. Kami menggabungkan disiplin teknikal dan pengalaman peribadi yang tenang.", primary: "Kenali kisah kami", secondary: "Temui kami di studio" },
    contact: { eyebrow: "KUNJUNGI MEZZANAIL NAIL STUDIO", title: "Janji temu seterusnya bermula di sini.", body: "Hubungi pasukan studio untuk cadangan servis, waktu janji temu atau bantuan keahlian.", address: "Studio", hours: "Waktu operasi", phone: "Hubungi", map: "Buka Peta", book: "Tempah janji temu", whatsapp: "WhatsApp pasukan kami" },
    footer: { line: "Penjagaan kuku moden, diperibadikan.", explore: "Teroka", connect: "Ikuti", studio: "Studio", privacy: "Privasi", terms: "Terma", copyright: "© 2026 Mezzanail Nail Studio. Hak cipta terpelihara." },
    pages: { services: { eyebrow: "MENU SERVIS", title: "Penjagaan tepat untuk tangan dan kaki.", body: "Lihat menu servis rasmi lengkap dengan harga semasa dan tempoh yang disenaraikan sebelum membuat tempahan.", cta: "Bincang servis anda" }, about: { eyebrow: "MEZZANAIL NAIL STUDIO · MALAYSIA", title: "Studio yang dibina atas perhatian.", body: "Pendekatan kami moden, tepat dan peribadi. Dari konsultasi hingga hasil akhir, setiap butiran dibuat tanpa kerumitan.", values: [["Ketepatan", "Teknik dan kemasan diberi perhatian yang sama."], ["Kesejahteraan", "Kesihatan kuku dan keselesaan pelanggan memandu setiap keputusan."], ["Kesederhanaan", "Hasil halus tidak memerlukan perkara berlebihan."]], cta: "Rancang kunjungan" }, contact: { eyebrow: "HUBUNGI & TEMPAHAN", title: "Hubungi pasukan studio kami.", body: "Beritahu servis, tarikh dan masa pilihan anda. Kami akan mengesahkan ketersediaan secara langsung.", formTitle: "Sebelum menghubungi", steps: ["Pilih kategori servis", "Kongsi tarikh dan masa pilihan", "Terima pengesahan pasukan kami"] } }
  }
} as const;

export type OfficialDictionary = (typeof officialMessages)[Locale];
