export const currentCampaign = {
  id: "mezzanail-7th-anniversary-2026",
  name: "Mezzanail 7th Anniversary Lucky Draw Campaign",
  desktopSrc: "/campaigns/7th-anniversary/banner-desktop.webp",
  mobileSrc: "/campaigns/7th-anniversary/banner-mobile.webp",
  alt: "Mezzanail 7th Anniversary Lucky Draw Campaign, 26 July to 30 September 2026",
  href: "/promotion",
  openInNewTab: false,
  priority: true,
  width: 1774,
  height: 887,
  mobileWidth: 1080,
  mobileHeight: 1080,
  heading: "Premium Nail Care in Melaka",
  campaignTitle: "Mezzanail 7th Anniversary",
  dates: "26 July – 30 September 2026",
  invitation: "Join the Lucky Draw",
  promotionLabel: "View Promotion",
  bookingLabel: "Book Now",
} as const;
